project:
  type: website
  output-dir: _site

website:
  title: "생각많은 소심남"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publication.qmd
        text: publication
    right: 
      - href: ../en
        text: En
      - href: https://github.com/goodboychan
        icon: github
      - href: https://www.linkedin.com/in/chanseokk/
        icon: linkedin

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



