project:
  type: website
  output-dir: _site

website:
  title: "생각많은 소심남"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right: 
      - href: ../en
        text: En

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



